const styles = {
	body: {
		fontFamily: '"Baloo 2" ,cursive',
		minHeight: '100vh',
		backgroundColor: '#E0E0E0',
		display: 'flex',
		flexDirection: 'column',
		padding: 20,
	},
	header: {
		backgroundColor: 'grey',
		height: 70,
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	right: {
		backgroundColor: '#F8BBD0',
		height: 50,
		width: 150,
		color: 'black',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	center: {
		backgroundColor: '#81D4FA',
		height: 50,
		width: 500,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	left: {
		backgroundColor: '#E1BEE7',
		height: 50,
		width: 120,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	main: {
		backgroundColor: 'lightBlue',
		display: 'flex',
		// flex: 2,
		height: 600,
		justifyContent: 'center',
		alignItems: 'center',
	},
	form: {
		height: 400,
		width: 400,
		backgroundColor: '#fff',
		borderRadius: 10,
		boxShadow: '2px 2px 10px #1e1e1e',
		justifyContent: 'center',
		alignItems: 'center',
	},
};
export default styles;